(needsLibraries '(LIB.Audio LIB.Maths))
(require 'libs/stdlib '$stdlib_)
(require 'libs/utils '$utils_)
(require 'libs/timer '$timer_)
(undef alarm)
(defun alarm (ttime)
  (while (<> ttime (left (time) 5)) (pause 1000))
  (while t (beep)(pause 250)(beep)(pause 1000))
)
(threadObject 'alarm)
(addMethod 'alarm "(run () (print self) (while (<> alarmtime (time (quote HH:mm))) (pause 1000) ) (play alarmSound) (pause 144000) (play alarmSong) (pause 600000) (play alarmSong2) )")
(undef setAlarm)
(defun setAlarm ()
  (alarmParams)
  (print "Heure d alarme (hh:mm)")
  (setq alarmtime (left (read) 5))
  (run 'alarm)
)
(undef setAlarmWT)
(defun setAlarmWT (wt)
  (alarmParams)
  (setq alarmtime (left wt 5))
  (run 'alarm)
  (print "L alarme a ete activee pour " wt " avec " alarmSound " en premier et " alarmSong " en second" )
)
